general:
  use_uvloop: true

functions:
  # Add your tools configuration here

llms:
  nim_llm:
    _type: nim
    model_name: meta/llama-3.1-70b-instruct
    temperature: 0.5

workflow:
  _type: react_agent
  tool_names: []  # List all tool names here
  llm_name: nim_llm
  verbose: true
  retry_parsing_errors: true
  max_retries: 3
