general:
  use_uvloop: true

functions:
  - _type: retrieval_agent
    description: 'Agent IQ retrieval tool for RAG chatbot.'
    parameters:
      input_message: FieldInfo(annotation=str, required=True)

llms:
  nim_llm:
    _type: nim
    model_name: meta/llama-3.1-70b-instruct
    temperature: 0.5

workflow:
  _type: react_agent
  tool_names: [retrieval_agent]
  llm_name: nim_llm
  verbose: true
  retry_parsing_errors: true
  max_retries: 3